### ISSUE TITLE
specify gdl_kernel license

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl_kernel#12]
@lstagner there seem to be no license specified for gdl_kernel code
Do you agree to cover the code with GPL v2 as is the case of GDL and GDLDE?

Also, we are drafting a short paper about GDL 1.0 to be submitted to the J. Open Source Software (https://joss.theoj.org/).
Please confirm, if you agree to be listed as co-author (and we will then include you in further communications concerning paper composition).

Thanks, 
Sylwester

**Comment by lstagner** [comment]
Go right ahead. Both with the license and the authorship.

**Comment by slayoo** [comment]
Thanks, @lstagner!
