### ISSUE TITLE
No Kernel

### ISSUE THREAD

**Issue by LanXtai** [gnudatalanguage/gdl_kernel#4]
Hello,
I'm sure it's a very low-level issue, but as I installed a gdl kernel, I tried to launch a notebook. The kernel was available, but it couldn't run, with this message :

`"[I 20:11:34.427 LabApp] KernelRestarter: restarting kernel (4/5), new random ports

C:\Users\jpmar\AppData\Local\Continuum\anaconda3\python.exe: No module named gdl_kernel

[W 20:11:37.536 LabApp] KernelRestarter: restart failed

[W 20:11:37.536 LabApp] Kernel 0c1553d1-d40c-4bb0-939f-7c7c4798f16c died, removing from map.

[W 20:12:22.339 LabApp] Timeout waiting for kernel_info reply from 0c1553d1-d40c-4bb0-939f-7c7c4798f16c

[E 20:12:22.340 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 0c1553d1-d40c-4bb0-939f-7c7c4798f16c)".`

How can I show Anaconda that this kernel does exist ?
Thanks.

**Comment by slayoo** [comment]
Well, certainly a good start would be to check if this works:
```
C:\Users\jpmar\AppData\Local\Continuum\anaconda3\python.exe
>>> import gdl_kernel
```
If not, perhaps try installing gdl_kernel by doing:
```
C:\Users\jpmar\AppData\Local\Continuum\anaconda3\python.exe setup.py install --prefix=~/.local
```
from within the gdl_kernel source directory.

HTH

**Comment by LanXtai** [comment]
As I couldn't import the kernel, I installed it with your second line. It seemed to work:

```
(base) C:\Users\jpmar\.jupyter\gdl_kernel-master>C:\Users\jpmar\AppData\Local\Continuum\anaconda3\python.exe setup.py install --prefix=~/.local
running install
running build
running build_py
running install_lib
running install_egg_info
Removing C:\Users\jpmar\.local\Lib\site-packages\GDL_kernel-0.5-py3.7.egg-info
Writing C:\Users\jpmar\.local\Lib\site-packages\GDL_kernel-0.5-py3.7.egg-info`
```

but after trying to import it again, I just had th following error : 

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\jpmar\.jupyter\gdl_kernel-master\gdl_kernel.py", line 4, in <module>
    from pexpect import replwrap,EOF,spawn
ModuleNotFoundError: No module named 'pexpect'
```

I also noticed that installing the kernel with the procedure detailed in Readme.md didn't create any file in `C:\Users\jpmar\AppData\Local\Continuum\anaconda3\share\jupyter\kernels` where I already have the Python3 kernel, but I got the gdl_kernel.py in `C:\Users\jpmar\.local\Lib\site-packages` according to the output of the installation.

Also (and sorry for forgetting to precise it) I'm trying it on a PC using Windows... It may change a few things...

**Comment by LanXtai** [comment]
Hi,
I just started using Ubuntu to see wether the problem would solve itself... Yet I always get the same errors. Here is a part of the reports I get, knowing that the kernel has correctly been installed (all files are in right directories and the command `import kernel` seems to work).
```
[I 15:56:55.858 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/home/lanxtai/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lanxtai/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lanxtai/.local/lib/python3.7/site-packages/gdl_kernel.py", line 209, in <module>
    IPKernelApp.launch_instance(kernel_class=GDLKernel)
  File "/home/lanxtai/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "</home/lanxtai/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-124>", line 2, in initialize
  File "/home/lanxtai/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/lanxtai/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 542, in initialize
    self.init_kernel()
  File "/home/lanxtai/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "/home/lanxtai/anaconda3/lib/python3.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/lanxtai/.local/lib/python3.7/site-packages/gdl_kernel.py", line 50, in __init__
    self._start_gdl()
  File "/home/lanxtai/.local/lib/python3.7/site-packages/gdl_kernel.py", line 70, in _start_gdl
    self.gdlwrapper = replwrap.REPLWrapper(self._child,u"GDL> ",None)
  File "/home/lanxtai/anaconda3/lib/python3.7/site-packages/pexpect/replwrap.py", line 44, in __init__
    self.child.setecho(False)
  File "/home/lanxtai/anaconda3/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 413, in setecho
    return self.ptyproc.setecho(state)
AttributeError: 'spawn' object has no attribute 'ptyproc'
[W 15:56:58.874 LabApp] KernelRestarter: restart failed
[W 15:56:58.874 LabApp] Kernel 6f3b633e-6043-41ad-9585-5498fb2a57e9 died, removing from map.
[W 15:57:02.624 LabApp] 404 GET /api/kernels/6f3b633e-6043-41ad-9585-5498fb2a57e9/channels?session_id=798b11fe-db9c-4f05-8e0f-43ff07d66af4&token=bffd1ef4c87f1c55f16fc3f6dad08a42b3d61fbe200294b7 (127.0.0.1): Kernel does not exist: 6f3b633e-6043-41ad-9585-5498fb2a57e9
[W 15:57:02.666 LabApp] 404 GET /api/kernels/6f3b633e-6043-41ad-9585-5498fb2a57e9/channels?session_id=798b11fe-db9c-4f05-8e0f-43ff07d66af4&token=bffd1ef4c87f1c55f16fc3f6dad08a42b3d61fbe200294b7 (127.0.0.1) 44.78ms referer=None
[W 15:57:02.670 LabApp] 404 GET /api/kernels/6f3b633e-6043-41ad-9585-5498fb2a57e9/channels?session_id=87b79bd4-5ccd-47de-b62c-7f34f022ccfb&token=bffd1ef4c87f1c55f16fc3f6dad08a42b3d61fbe200294b7 (127.0.0.1): Kernel does not exist: 6f3b633e-6043-41ad-9585-5498fb2a57e9
[W 15:57:02.671 LabApp] 404 GET /api/kernels/6f3b633e-6043-41ad-9585-5498fb2a57e9/channels?session_id=87b79bd4-5ccd-47de-b62c-7f34f022ccfb&token=bffd1ef4c87f1c55f16fc3f6dad08a42b3d61fbe200294b7 (127.0.0.1) 3.80ms referer=None
[W 15:57:05.306 LabApp] Timeout waiting for kernel_info reply from 9e5e79b4-e81d-47e2-994c-3c0f03cbcbba
[E 15:57:05.308 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 9e5e79b4-e81d-47e2-994c-3c0f03cbcbba)
[W 15:57:43.873 LabApp] Timeout waiting for kernel_info reply from 6f3b633e-6043-41ad-9585-5498fb2a57e9
[E 15:57:43.874 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 6f3b633e-6043-41ad-9585-5498fb2a57e9)
```

**Comment by slayoo** [comment]
This seems to be the same issue as reported here: https://github.com/lstagner/idl_kernel/issues/2
There, the conclusion was that IDL was not installed. Could you double check if python can find the gdl binary by trying:
```python
from distutils.spawn import find_executable
print(find_executable("gdl"))
```

**Comment by LanXtai** [comment]
Indeed, the command returns "None" ; but `hash -r` wouldn't solve the problem and I believe the kernel was installed : `import gdl_kernel` seemed to work and `jupyter kernelspec list` returns it as a known kernel... Plus I installed the GDL kernel several times...

**Comment by slayoo** [comment]
The kernel installation and GDL installation are separate things.
Are you able to launch gdl from command line?

**Comment by LanXtai** [comment]
Indeed I didn't install GDL as I believed that the kernel would be sufficient... I installed it and now it works, I just didn't realize they were two separate tasks... Thank you very much for the help !
